<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Captura.Core\Captura.Core.csproj" />
    <ProjectReference Include="..\Screna\Screna.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FFMpegCore" Version="5.2.0" />
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
    <PackageReference Include="ReactiveProperty" Version="9.7.0" />
  </ItemGroup>
</Project>
