<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="PresentationCore" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Captura.Base\Captura.Base.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="keymaps\*.json" Exclude="keymaps\schema.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FFMpegCore" Version="5.2.0" />
    <PackageReference Include="MouseKeyHook" Version="5.7.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
    <PackageReference Include="System.Reactive" Version="6.0.1" />
  </ItemGroup>
</Project>